# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/HelloWord',
                'doc_host': 'https://Paul-Rochette.github.io',
                'git_url': 'https://github.com/Paul-Rochette/HelloWord',
                'lib_path': 'HelloWord'},
  'syms': {'HelloWord.core': {'HelloWord.core.foo': ('core.html#foo', 'HelloWord/core.py')}}}
