# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_new_core.ipynb.

# %% auto 0
__all__ = ['addition', 'foo']

# %% ../nbs/01_new_core.ipynb 2
def addition(a,b): 
    return a+b

# %% ../nbs/01_new_core.ipynb 4
def foo(): pass
